### ISSUE TITLE
Fix pdf open process for TeX compile command

### ISSUE THREAD

**Issue by AkkeyLab** [AkkeyLab/mac-auto-setup#55]
![screen shot 2017-07-17 at 12 12 05](https://user-images.githubusercontent.com/17640999/28254637-65e33d00-6ae9-11e7-9713-31c8fc94b738.png)

`${file}.pdf;` -> FIleName.tex.pdf

**Comment by arabian9ts** [comment]
`$(file)` is not replaced to name which has no extension.
please refer to #56
